### ISSUE TITLE
Use astroquery.utils.tap rather than making out own URL calls

### ISSUE THREAD

**Issue by Cadair** [sunpy/sunpy-soar#32]
### Provide a general description of the issue or problem.

https://astroquery.readthedocs.io/en/latest/utils/tap.html

**Comment by dstansby** [comment]
I just had a quick look into this, and the following code errors, and I'm not sure what the solution is. Thought I'd leave this here as a paper trail though.

```python
from astroquery.utils.tap.core import TapPlus

soar = TapPlus('http://soar.esac.esa.int/soar-sl-tap/tap')
tables = soar.load_tables(only_names=True)
for table in (tables):
    print(table.get_qualified_name())

table = soar.load_table('time_series.time_series.v_solo_ll02_swapasmom_2')
print(table)
```

with 

```python
Retrieving table 'time_series.time_series.v_solo_ll02_swapasmom_2'
500 Error 500:
esavo.tap.TAPException: esavo.tap.TAPException: Schema cannot be null
Traceback (most recent call last):
  File "/Users/dstansby/github/sunpy-soar/test.py", line 8, in <module>
    table = soar.load_table('time_series.time_series.v_solo_ll02_swapasmom_2')
  File "/Users/dstansby/mambaforge/envs/sunpy/lib/python3.10/site-packages/astroquery/utils/tap/core.py", line 177, in load_table
    self.__connHandler.check_launch_response_status(response,
  File "/Users/dstansby/mambaforge/envs/sunpy/lib/python3.10/site-packages/astroquery/utils/tap/conn/tapconn.py", line 683, in check_launch_response_status
    raise requests.exceptions.HTTPError(errMsg)
requests.exceptions.HTTPError: Error 500:
esavo.tap.TAPException: esavo.tap.TAPException: Schema cannot be null
```

**Comment by Cadair** [comment]
I asked Helen and she said to drop the part before the first `.` which apparently is the schema.

**Comment by Cadair** [comment]
```
>>> table = soar.load_table('time_series.v_solo_ll02_swapasmom_2')
>>> print(table)
Retrieving table 'time_series.v_solo_ll02_swapasmom_2'
TAP Table name: time_series.time_series.v_solo_ll02_swapasmom_2
Description: 
Num. columns: 3
```

**Comment by herroyalmaj** [comment]
Hey there :) herroyalmaj

**Comment by Cadair** [comment]
I have had some success:
```
In [51]: job = soar.launch_job(f"SELECT * FROM v_sc_data_item WHERE (descriptor='{descriptor}') AND (begin_time>='{cme_start}') AND (end_time<='{cme_end}')")

In [52]: job.results
Out[52]: 
<Table length=36>
       begin_time                       data_item_id                data_item_oid data_type    descriptor    ... postcard_item_oid        prop_end       sc_begin_time sc_end_time sensor
         object                            object                       int64       object       object      ...       int64               object            str10        str10    object
----------------------- ------------------------------------------- ------------- --------- ---------------- ... ----------------- --------------------- ------------- ----------- ------
2022-03-28T13:50:15.226 solo_L2_eui-fsi304-image_20220328T135015226        460311       SCI EUI-FSI304-IMAGE ...            224221 1900-01-01T00:00:00.0                                 
2022-03-28T13:40:15.226 solo_L2_eui-fsi304-image_20220328T134015226        460310       SCI EUI-FSI304-IMAGE ...            224220 1900-01-01T00:00:00.0                                 
2022-03-28T13:30:15.225 solo_L2_eui-fsi304-image_20220328T133015225        460309       SCI EUI-FSI304-IMAGE ...            224219 1900-01-01T00:00:00.0                                 
2022-03-28T13:20:15.224 solo_L2_eui-fsi304-image_20220328T132015224        460308       SCI EUI-FSI304-IMAGE ...            224218 1900-01-01T00:00:00.0                                 
2022-03-28T13:10:15.222 solo_L2_eui-fsi304-image_20220328T131015222        460307       SCI EUI-FSI304-IMAGE ...            224216 1900-01-01T00:00:00.0                                 
2022-03-28T13:00:15.219 solo_L2_eui-fsi304-image_20220328T130015219        460306       SCI EUI-FSI304-IMAGE ...            224217 1900-01-01T00:00:00.0                                 
 2022-03-28T12:50:15.22 solo_L2_eui-fsi304-image_20220328T125015220        460305       SCI EUI-FSI304-IMAGE ...            224215 1900-01-01T00:00:00.0                                 
 2022-03-28T12:40:15.22 solo_L2_eui-fsi304-image_20220328T124015220        460304       SCI EUI-FSI304-IMAGE ...            224211 1900-01-01T00:00:00.0                                 
2022-03-28T12:30:15.218 solo_L2_eui-fsi304-image_20220328T123015218        460303       SCI EUI-FSI304-IMAGE ...            224213 1900-01-01T00:00:00.0                                 
                    ...                                         ...           ...       ...              ... ...               ...                   ...           ...         ...    ...
2022-03-28T12:20:15.217 solo_L1_eui-fsi304-image_20220328T122015217        329158       SCI EUI-FSI304-IMAGE ...                -- 1900-01-01T00:00:00.0                                 
2022-03-28T12:10:15.216 solo_L1_eui-fsi304-image_20220328T121015216        329157       SCI EUI-FSI304-IMAGE ...                -- 1900-01-01T00:00:00.0                                 
2022-03-28T12:00:15.213 solo_L1_eui-fsi304-image_20220328T120015213        329156       SCI EUI-FSI304-IMAGE ...                -- 1900-01-01T00:00:00.0                                 
2022-03-28T11:50:15.214 solo_L1_eui-fsi304-image_20220328T115015214        329155       SCI EUI-FSI304-IMAGE ...                -- 1900-01-01T00:00:00.0                                 
2022-03-28T11:40:15.213 solo_L1_eui-fsi304-image_20220328T114015213        329154       SCI EUI-FSI304-IMAGE ...                -- 1900-01-01T00:00:00.0                                 
2022-03-28T11:30:15.212 solo_L1_eui-fsi304-image_20220328T113015212        329153       SCI EUI-FSI304-IMAGE ...                -- 1900-01-01T00:00:00.0                                 
2022-03-28T11:20:15.209 solo_L1_eui-fsi304-image_20220328T112015209        329152       SCI EUI-FSI304-IMAGE ...                -- 1900-01-01T00:00:00.0                                 
 2022-03-28T11:10:15.21 solo_L1_eui-fsi304-image_20220328T111015210        329151       SCI EUI-FSI304-IMAGE ...                -- 1900-01-01T00:00:00.0                                 
2022-03-28T11:00:15.209 solo_L1_eui-fsi304-image_20220328T110015209        329150       SCI EUI-FSI304-IMAGE ...                -- 1900-01-01T00:00:00.0                                 

```

**Comment by ebuchlin** [comment]
Maybe irrelevant now that use of `astroquery.utils.tap` is considered: a first step (with no additional dependency) could be to build the ADQL query without building the full URL explicitly (as currently done in [`_construct_url()`](https://github.com/sunpy/sunpy-soar/blob/924cac57c80dc28c9b770b30cd4935af5851c4bf/sunpy_soar/client.py#L34), then use something like
```python
        tap_end_point = 'http://soar.esac.esa.int/soar-sl-tap/tap/'
        payload = {
            'REQUEST': 'doQuery',
            'LANG': 'ADQL',
            'FORMAT': 'json',
            'QUERY': adql_query
        }
        r = requests.get(f'{tap_end_point}/sync', params=payload)
```
This is more clear and maintainable, the ADQL query is automatically URL-escaped, and you can still get the actual full URL with `r.url`.

**Comment by ebuchlin** [comment]
I just learned from @herroyalmaj that [TapPlus](https://astroquery.readthedocs.io/en/latest/utils/tap.html) now recommends to use [PyVO](https://pyvo.readthedocs.io/en/latest/) instead.

I would say that it doesn't change much to PR#129, as most of line changes in that PR were to make the ADQL queries non-URL-escaped. The transition to PyVO should then not be too difficult as a next step.

**Comment by nabobalis** [comment]
In that case we should update the current PR to use that.

**Comment by Cadair** [comment]
This came up again in the discussion around #196.

I wonder if the thread that seemed to be the hangup on https://github.com/sunpy/sunpy-soar/pull/129#issuecomment-2224312091 got fixed server-side or anything?

**Comment by samaloney** [comment]
So looking at the code 

https://github.com/sunpy/sunpy-soar/blob/22d031cd126ca817f3172ac662de113eeb94244c/sunpy_soar/client.py#L156-L172

and the issue opened upstream https://github.com/astropy/pyvo/issues/579 this would still require a bit of a work around

```
service = vo.dal.TAPService("http://soar.esac.esa.int/soar-sl-tap/tap")
query = service.create_query("select top 10 * from time_series.v_solo_ll02_mag_0")
query
{'REQUEST': 'doQuery',
 'LANG': 'ADQL',
 'QUERY': 'select top 10 * from time_series.v_solo_ll02_mag_0'}
query['REQUEST'] = 'doQueryFilteredByDistance'
```

But I can't even find documentation the [SOAR](https://www.cosmos.esa.int/web/soar/metadata-request) about `doQuery` vs `doQueryFilteredByDistance`?

**Comment by Cadair** [comment]
Well that work around isn't terrible?

**Comment by samaloney** [comment]
Unfortunately it doesn't work 💢  - the distance part is not part of the ADQL spec is basically just an extra query parameter. I think it probably possible to create a subclass of `TAPClient` but not 100% sure.

**Comment by Cadair** [comment]
Ok, so let's punt this to post-merge then. Looks like it's something we should work with upstream on anyway.

**Comment by ebuchlin** [comment]
I believe we can keep the call to `requests.get()` as it is, at least is makes proper use of the payload argument, and the ADQL query part is clearly separated from the rest. PyVO might be slightly higher-level, but it can't do what we want to do. Also [nobody seems to know whether `REQUEST=doQueryFilteredByDistance` and SOAR (ESA TAP+) conform to some version of the TAP standard](https://github.com/sunpy/sunpy-soar/issues/134#issuecomment-2225126549), so this could explain why PyVO can't do what we ask it to do.

**Comment by samaloney** [comment]
Yea so this is an MVP which work would need do the same for the asyn version and maybe a few other things

```python
from functools import partial

import requests
from pyvo.dal.tap import TAPQuery, TAPResults, TAPService

class SOARTAPQuery(TAPQuery):
    def __init__(self, *args, distance=None, **kwargs):
        super().__init__(*args, **kwargs)
        self._distance = distance  # e.g. (0.45, 0.46)

    def submit(self, *, post=False):
        url = self.queryurl
        tmp = self.copy()

        if self._distance:
            tmp["REQUEST"] = 'doQueryFilteredByDistance'

        if post:
            files = {
                upload.name: upload.fileobj()
                for upload in self._uploads
                if upload.is_inline
            }
            response = self._session.post(url, data=tmp, stream=True, files=files)
        else:
            # Use requests to properly encode params, then append &DISTANCE() raw
            prepared = requests.Request("GET", url, params=dict(tmp)).prepare()
            get_url = prepared.url
            if self._distance:
                get_url += f"&DISTANCE({self._distance[0]},{self._distance[1]})"
            response = self._session.get(get_url, stream=True)

        response.raw.read = partial(response.raw.read, decode_content=True)
        return response

class SOARTAPService(TAPService):
    def search(self, query, distance=None, **kwargs):
        q = SOARTAPQuery(
            self.baseurl,
            query,
            session=self._session,
            **kwargs
        )
        if distance:
            q._distance = distance
        return q.execute()

service = SOARTAPService("http://soar.esac.esa.int/soar-sl-tap/tap")

results = service.search("SELECT TOP 100 h1.instrument,h1.descriptor,h1.level,h1.begin_time,h1.end_time,h1.data_item_id,"
                         "h1.filesize,h1.filename,h1.soop_name,h2.detector,h2.wavelength,h2.dimension_index "
                         "FROM v_sc_data_item AS h1 JOIN v_eui_sc_fits AS h2 USING (data_item_oid) "
                         "WHERE h1.instrument = 'EUI' AND h1.level = 'L2' AND h2.Detector = 'HRI_EUV'")
print(results.to_qtable()['filename'])


results_dsit = service.search("SELECT TOP 100 h1.instrument,h1.descriptor,h1.level,h1.begin_time,h1.end_time,h1.data_item_id,"
                         "h1.filesize,h1.filename,h1.soop_name,h2.detector,h2.wavelength,h2.dimension_index "
                         "FROM v_sc_data_item AS h1 JOIN v_eui_sc_fits AS h2 USING (data_item_oid) "
                         "WHERE h1.instrument = 'EUI' AND h1.level = 'L2' AND h2.Detector = 'HRI_EUV'",
                         distance=(0.45, 0.46))
print(results_dsit.to_qtable()['filename'])

```
